---
# tasks file for dev_tools
- name: Install development tools
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - openssh-client
    - openssh-server
    - apt-transport-https  
    - wget
    - gpg  
    - zsh
    - git
    - vim
    - xcape  
    - fonts-powerline
    - fzf  
    - build-essential
    - htop
    - vlc
    - tilix
    - sysstat
    - glances

- name: Increase sudo timeout and validate
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    regexp: '^Defaults\s*env_reset'
    line: 'Defaults env_reset,timestamp_timeout=60'
    validate: /usr/sbin/visudo -cf %s    

- name: Prevent root login with password
  ansible.builtin.replace:
    path: /etc/ssh/sshd_config
    regexp: '^#PermitRootLogin (prohibit-password|yes|no)$'
    replace: 'PermitRootLogin prohibit-password'

- name: Prevent password login password
  ansible.builtin.replace:
    path: /etc/ssh/sshd_config
    regexp: '^#PasswordAuthentication (yes|no)$'
    replace: 'PasswordAuthentication no'

- name: Prevent password login password
  ansible.builtin.replace:
    path: /etc/ssh/sshd_config
    regexp: '^#PermitEmptyPasswords (yes|no)$'
    replace: 'PermitEmptyPasswords no'
  notify: restart sshd

- name: Create symlink to vte shell (for zsh)
  ansible.builtin.file:
    src: /etc/profile.d/vte-2.91.sh
    dest: /etc/profile.d/vte.sh
    state: link

- name: configure vundle package manager for git
  ansible.builtin.git:
    repo: https://github.com/VundleVim/Vundle.vim.git
    dest: '{{ home_dir }}/.vim/bundle/Vundle.vim' 

- name: configure git
  git_config:
    name: user.email
    scope: global
    value: 'brian.leach.6@gmail.com'
  vars:
    ansible_user: '{{ user_name }}'
    ansible_become: false    

- name: configure git continued
  git_config:
    name: user.name
    scope: global
    value: 'Brian Leach'
  vars: 
    ansible_user: '{{ user_name }}'
    ansible_become: false    

- name: Install Oh My Zsh
  shell: sh -c "$(wget -O- https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  args:
    creates: "{{ home_dir }}/.oh-my-zsh"
  become_user: "{{ user_name }}"

- name: Change user shell
  ansible.builtin.command: 'chsh --shell /bin/zsh {{ user_name }}'

- name: Install profiles and shell scripts
  ansible.builtin.copy:
    src: 'files/{{ item.name }}'
    dest: '{{ home_dir}}/.{{ item.name }}'
  loop:
    - name: 'vimrc'
    - name: 'zpreztorc'
    - name: 'zshrc'
    - name: 'zprofile'
  vars:
    ansible_user: '{{ user_name }}'  
    ansible_become: false  

- name: install zprezto
  ansible.builtin.git:
    repo: https://github.com/sorin-ionescu/prezto.git
    dest: '{{ home_dir }}/.zprezto'  

- name: Install vscode
  ansible.builtin.shell:
    cmd: 'wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > packages.microsoft.gpg'
    chdir: '{{ home_dir }}'  

- name: Install vscode continued
  ansible.builtin.command:
    cmd: 'install -D -o root -g root -m 644 packages.microsoft.gpg /etc/apt/keyrings/packages.microsoft.gpg'
    chdir: '{{ home_dir }}'  

- name: VScode key addition
  ansible.builtin.shell:
    cmd: 'echo "deb [arch=amd64,arm64,armhf signed-by=/etc/apt/keyrings/packages.microsoft.gpg] https://packages.microsoft.com/repos/code stable main" > /etc/apt/sources.list.d/vscode.list'  

- name: remove gpg key from microsoft
  ansible.builtin.shell:
    cmd: 'rm -rf packages.microsoft.gpg'
    chdir: '{{ home_dir }}'

- name: update cache
  ansible.builtin.apt:
    name: code
    update_cache: yes

- name: DEBUG
  ansible.builtin.debug:
    msg: 'here is user: {{ ansible_env.USER }}, home: {{ ansible_env}}'
  vars:
    ansible_become: false 
    ansible_user: '{{ user_name }}'

- name: more debug
  command: 'ls -lah {{ home_dir }}'
  vars:
    ansible_become: false  
 
